[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug", "-lxcm=trace" ]
chain = "polkadot-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9800
    validator = true
    args = ["--state-cache-size=0"]

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9801
    validator = true

[[parachains]]
id = 1300
chain= "glutton-kusama-local-1300"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 1300
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0", "-lglutton=debug", "-lnacho=debug", "-lrpc_metrics=trace" ]

[[parachains]]
id = 1301
chain= "glutton-kusama-local-1301"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 1301
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0", "-lglutton=debug", "-lnacho=debug", "-lrpc_metrics=trace" ]
