[relaychain]
default_command = "./bin/polkadot"
chain = "polkadot-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9800
    validator = true

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9801
    validator = true

[[parachains]]
id = 1300
chain= "glutton-kusama-local-1300"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 1300
    command = "./bin/polkadot-parachain"
    args = [ "-lcumulus-colator=info" ]

[[parachains]]
id = 1301
chain= "glutton-kusama-local-1301"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 1301
    command = "./bin/polkadot-parachain"
    args = [ "-lcumulus-colator=info" ]
